spring.application.name=ecommerce
server.address=0.0.0.0
server.port=8083

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/livraison1
spring.datasource.username=clarisse
spring.datasource.password=clarisse
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Logging Configuration
# logging.file.name=logs/livraison1.log
logging.level.root=INFO
logging.file.name=C:/temp/livraison1.log
logging.level.org.example.recensement=DEBUG

# SonarQube Configuration (Commented out)
#sonar.projectKey=demo5
#sonar.host.url=http://localhost:9000
#sonar.login=sqp_bddda9762de5eeacfb970498a9ba82e4e476dc74